### PR TITLE
Changed the example for the for in loop. Think mine is better.

### PR DESCRIPTION
**Pull request by interglobalmedia**
Hey Wes,

I think that instead of having 
```
for(const index in cuts) {
   console.log(cuts[index]);
 }
```
as your example of a for in loop in intro.html for Iterables & Loops, perhaps this would read better:

```
for (const cut in cuts) { 
    console.log(cuts[cut]); 
 }
```
Thanks!

### CODE REVIEW

**Comment by wesbos** [comment]
thanks - I use index because the cut variable would mean that would be the actual cut, not the index.

Going to close this one because I need to keep the examples 1:1 to the videos

**Comment by interglobalmedia** [comment]
No prob Wes. But this example does not return an index, but the cut!

**Comment by wesbos** [comment]
It doesn't return anything - it ust logs the cut. The important part is that the loop doesn't give us the cut, the loop gives us the index. If you want a cut variable, we would do `const cut = cuts[index];`

**Comment by interglobalmedia** [comment]
Or as I had in my example,
 for (const cut in cuts) { 
    console.log(cuts[cut]);
}
Same difference. Just another way of doing it. But I understand you want to keep it in sync with the videos! Thanks!

**Comment by wesbos** [comment]
👍🏻 thanks!

**Pull request closed without merging**
